### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by brhanna1** [bitfocus/companion-module-techministry-spotifycontroller#1]
Can't get feedback to work in companion. Not trying to see track time, just current state of playhead (playing, paused, stopped). Polling is set to on.

**Comment by josephdadams** [comment]
Would be helpful to know which version of Spotify-controller and which version of the module in companion

**Comment by ecobb125** [comment]
I am having the same issue - controller v0.2.0 & module v1.0.4

**Comment by josephdadams** [comment]
Roll back to controller 0.1.9 and it works fine
