### ISSUE TITLE
Move Player Position

### ISSUE THREAD

**Issue by ecobb125** [bitfocus/companion-module-techministry-spotifycontroller#2]
Moving player position with rotary encoder on stream deck + not working. Module v1.0.4, controller v0.1.9.

**Comment by josephdadams** [comment]
Probably too much to ask of the device. Keep in mind that in order to control Spotify at all in this way, we have to execute an AppleScript. So if you try to use a rotary encoder to quickly skip through a track, for example, every single turn of the encoder fires off a new AppleScript.
