### ISSUE TITLE
Shuffle and Repeat Variables don't seem to work

### ISSUE THREAD

**Issue by chawkins117** [bitfocus/companion-module-techministry-spotifycontroller#7]
I get a "False" return for the Repeat and Shuffle variables regardless of Spotify state. "Player State" is working as expected as well as Album Artist, Track Name, etc. The Repeat and Shuffle ON/OFF actions are working, just not the variable info.

**Comment by josephdadams** [comment]
Thank you for reporting this. I have fixed this in `v2.1.1` of the `techministry-spotifycontroller` module in Companion.
